[project]
name = "euroleague-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "httpx>=0.28.1",
    "ipython>=9.5.0",
    "ruff>=0.13.2",
    "uvicorn>=0.37.0",
]
