# Generated by Django 5.2.9 on 2026-01-16 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('game_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('Regular Season', 'Regular Season'), ('Play-In', 'Play-In'), ('Playoffs', 'Playoffs'), ('Final Four', 'Final Four')], default='Regular Season', max_length=20)),
                ('round', models.PositiveIntegerField()),
                ('utc_date', models.DateTimeField()),
                ('local_timezone', models.IntegerField()),
                ('home_team_code', models.CharField(max_length=3)),
                ('away_team_code', models.CharField(max_length=3)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_score', models.PositiveIntegerField(default=None, null=True)),
                ('away_score', models.PositiveIntegerField(default=None, null=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('audience', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('passport_name', models.CharField(blank=True, max_length=50)),
                ('passport_surname', models.CharField(blank=True, max_length=50)),
                ('jersey_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(null=True)),
                ('weight', models.PositiveIntegerField(null=True)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('type_name', models.CharField(blank=True, max_length=30)),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='euroleague.club')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter', models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter'), ('Extra Time', 'Extra Time')], default='First Quarter', max_length=20)),
                ('number_of_play', models.PositiveIntegerField()),
                ('play_team', models.CharField(max_length=50, null=True)),
                ('play_type', models.CharField(choices=[('BP', 'BP'), ('EP', 'EP'), ('JB', 'JB'), ('FTA', 'FTA'), ('FTM', 'FTM'), ('2FGA', '2FGA'), ('2FGM', '2FGM'), ('3FGA', '3FGA'), ('3FGM', '3FGM'), ('AG', 'AG'), ('D', 'D'), ('O', 'O'), ('TO', 'TO'), ('AS', 'AS'), ('FV', 'FV'), ('ST', 'ST'), ('CM', 'CM'), ('RV', 'RV'), ('OF', 'OF'), ('CMTI', 'CMTI'), ('TOUT', 'TOUT'), ('TOUT_TV', 'TOUT_TV'), ('CMD', 'CMD'), ('CMT', 'CMT'), ('CMU', 'CMU'), ('C', 'C'), ('B', 'B'), ('CCH', 'CCH'), ('IN', 'IN'), ('OUT', 'OUT'), ('EG', 'EG')], default='BP', max_length=20)),
                ('game_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('game_time', models.PositiveIntegerField(blank=True, null=True)),
                ('home_team_play_points', models.PositiveIntegerField(default=None, null=True)),
                ('away_team_play_points', models.PositiveIntegerField(default=None, null=True)),
                ('play_info', models.CharField(blank=True, max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_play', to='euroleague.match')),
                ('player', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='euroleague.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'number_of_play'), name='unique_play_per_match')],
            },
        ),
    ]
