# Generated by Django 5.2.9 on 2026-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Guard', 'Guard'), ('Forward', 'Forward'), ('Center', 'Center')], default='Guard', max_length=20),
        ),
    ]
