# Generated by Django 5.2.9 on 2025-12-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
