# Generated by Django 5.2.9 on 2026-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0002_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Guard', 'Guard'), ('Forward', 'Forward'), ('Center', 'Center')], default='Guard', max_length=20, null=True),
        ),
    ]
