# Generated by Django 5.2.9 on 2025-12-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0002_alter_club_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('passport_name', models.CharField(blank=True, max_length=50)),
                ('passport_surname', models.CharField(blank=True, max_length=50)),
                ('jersey_name', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
    ]
