# Generated by Django 5.2.9 on 2025-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
