# Generated by Django 5.2.9 on 2026-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0003_alter_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='away_team_play_points',
            new_name='away_team_points',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='home_team_play_points',
            new_name='home_team_points',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='type_name',
            new_name='role',
        ),
    ]
