# Generated by Django 5.2.9 on 2025-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0004_alter_player_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
