# Generated by Django 5.2.9 on 2026-01-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0001_squashed_0004_delete_match_rename_code_club_club_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_code',
            new_name='code',
        ),
    ]
