# Generated by Django 5.2.9 on 2026-01-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0005_rename_club_code_club_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.CharField(max_length=30)),
                ('gamecode', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phase', models.CharField(max_length=20)),
                ('round', models.IntegerField(default=None, null=True)),
                ('utc_date', models.DateTimeField()),
                ('local_timezone', models.IntegerField()),
                ('home_team_code', models.CharField(max_length=3)),
                ('away_team_code', models.CharField(max_length=3)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_score', models.IntegerField(default=None, null=True)),
                ('away_score', models.IntegerField(default=None, null=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('audience', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
