# Generated by Django 5.2.9 on 2025-12-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0005_alter_player_jersey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='euroleague.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
