# Generated by Django 5.2.9 on 2026-01-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0006_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
    ]
