# Generated by Django 5.2.9 on 2026-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0007_alter_match_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='gamecode',
        ),
        migrations.AddField(
            model_name='match',
            name='game_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('Regular Season', 'Regular Season'), ('Play-In', 'Play-In'), ('Playoffs', 'Playoffs'), ('Final Four', 'Final Four')], default='Regular Season', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
