# Generated by Django 5.2.9 on 2026-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0008_remove_match_gamecode_match_game_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(),
        ),
    ]
