# Generated by Django 5.2.9 on 2026-01-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0009_alter_match_game_code_alter_match_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter', models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter'), ('Extra Time', 'Extra Time')], default='First Quarter', max_length=20)),
                ('number_of_play', models.IntegerField(unique=True)),
                ('play_team', models.CharField(max_length=50)),
                ('play_type', models.CharField(choices=[('BP', 'BP'), ('EP', 'EP'), ('JB', 'JB'), ('FTA', 'FTA'), ('FTM', 'FTM'), ('2FGA', '2FGA'), ('2FGM', '2FGM'), ('3FGA', '3FGA'), ('3FGM', '3FGM'), ('D', 'D'), ('O', 'O'), ('TO', 'TO'), ('AS', 'AS'), ('FV', 'FV'), ('ST', 'ST'), ('CM', 'CM'), ('OF', 'OF'), ('TOUT', 'TOUT'), ('TOUT-TV', 'TOUT-TV'), ('CMT', 'CMT'), ('CMU', 'CMU'), ('IN', 'IN'), ('OUT', 'OUT'), ('EG', 'EG')], default='BP', max_length=20)),
                ('marker_time', models.TimeField(blank=True)),
                ('home_team_play_points', models.IntegerField(default=None, null=True)),
                ('away_team_play_points', models.IntegerField(default=None, null=True)),
                ('play_info', models.CharField(blank=True, max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_play', to='euroleague.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='euroleague.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'number_of_play'), name='unique_play_per_match')],
            },
        ),
    ]
