# Generated by Django 5.2.9 on 2026-01-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0010_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='type_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
